language: dart
sudo: true
dist: xenial
os:
  - linux
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - flutter build apk
cache:
  directories:
    - $HOME/.pub-cache